base_config: ../scannet_og/scannet_og_hybrid_v14_scene0062_00.yaml
scene_root: /mnt/pool/sqy/3d_understanding/scannet_og/scene0062_00
rgb_dir: /mnt/pool/sqy/3d_understanding/scannet_og/scene0062_00/color
val_rgb_dir: /mnt/pool/sqy/3d_understanding/scannet_og/scene0062_00/color
feature_dir: /mnt/pool/sqy/results/RADIO-GS/output/optimization_20260815/core_method_v1/scene0062_00/source_radio_features
val_feature_dir: /mnt/pool/sqy/results/RADIO-GS/output/optimization_20260815/core_method_v1/scene0062_00/source_radio_features
feature_height: 60
feature_width: 81
pose_file: /mnt/pool/sqy/3d_understanding/scannet_og/scene0062_00/traj_w_c.txt
val_pose_file: /mnt/pool/sqy/3d_understanding/scannet_og/scene0062_00/traj_w_c.txt
pose_dir: ""
val_pose_dir: ""
train_frame_ids_path: /mnt/pool/sqy/3d_understanding/scannet_og/scene0062_00/splits/train_frames.txt
val_frame_ids_path: /mnt/pool/sqy/3d_understanding/scannet_og/scene0062_00/splits/val_frames.txt
