"""Shared query interface for the canonical RADIO-GS feature field."""

from .unified_query import (
    QueryKind,
    QuerySpace,
    QuerySpec,
    SupportGraph,
    SupportPropagationConfig,
    binary_mask,
    build_support_graph,
    cosine_bank_torch,
    cosine_margin_torch,
    cosine_relevancy_torch,
    margin_to_relevancy_torch,
    propagate_support,
    seed_connected_component,
    score_feature_map,
    score_features,
)
from .query_engine import CanonicalQueryEngine, QueryResult
from .score_calibration import (
    SceneSpaceCalibration,
    deterministic_sample_rows,
    fit_scene_space_calibration,
    robust_tanh_score_calibration,
)
from .evidence_scorer import (
    fuse_registered_observation_unary,
    registered_observation_anchor_only_confidence,
    registered_observation_anchor_mask,
    registered_observation_effective_confidence,
    registered_seed_observation,
    registered_seed_unary,
    registered_raster_adjoint_observation,
    shrink_unary_by_reliability,
)
from .query_compilers import compile_registered_primitive_seeds
from .reliability_fusion import (
    geometric_consensus_unary,
    symmetric_bernoulli_product_of_experts,
)
from .query_spec import (
    PrimitiveUnaryEvidence,
    PrototypeSet,
    QueryIntent,
    QueryModality,
    QuerySpec as TypedQuerySpec,
    RegistrationMode,
    SelectionMode,
    SoftSeedGroups,
    SoftSeedSet,
)
from .support_solver import (
    PrimitiveSupportGraph,
    SupportGraphConfig,
    SupportSolverConfig,
    build_primitive_support_graph,
    graph_for_query_intent,
    mix_support_graph_channels,
    select_support_components,
    solve_primitive_support,
)

__all__ = [
    "QueryKind",
    "QuerySpace",
    "QuerySpec",
    "SupportGraph",
    "SupportPropagationConfig",
    "binary_mask",
    "build_support_graph",
    "cosine_bank_torch",
    "cosine_margin_torch",
    "cosine_relevancy_torch",
    "margin_to_relevancy_torch",
    "propagate_support",
    "seed_connected_component",
    "score_feature_map",
    "score_features",
    "CanonicalQueryEngine",
    "PrimitiveSupportGraph",
    "PrimitiveUnaryEvidence",
    "PrototypeSet",
    "QueryIntent",
    "QueryModality",
    "QueryResult",
    "SceneSpaceCalibration",
    "deterministic_sample_rows",
    "fit_scene_space_calibration",
    "robust_tanh_score_calibration",
    "RegistrationMode",
    "SelectionMode",
    "SoftSeedGroups",
    "SoftSeedSet",
    "SupportGraphConfig",
    "SupportSolverConfig",
    "TypedQuerySpec",
    "build_primitive_support_graph",
    "compile_registered_primitive_seeds",
    "graph_for_query_intent",
    "mix_support_graph_channels",
    "registered_seed_unary",
    "registered_raster_adjoint_observation",
    "registered_seed_observation",
    "registered_observation_anchor_mask",
    "registered_observation_anchor_only_confidence",
    "registered_observation_effective_confidence",
    "fuse_registered_observation_unary",
    "geometric_consensus_unary",
    "select_support_components",
    "symmetric_bernoulli_product_of_experts",
    "solve_primitive_support",
    "shrink_unary_by_reliability",
]
