"""Shared query interface for the canonical RADIO-GS feature field."""

from .unified_query import (
    QueryKind,
    QuerySpace,
    QuerySpec,
    SupportGraph,
    SupportPropagationConfig,
    binary_mask,
    build_support_graph,
    cosine_bank_torch,
    cosine_margin_torch,
    cosine_relevancy_torch,
    margin_to_relevancy_torch,
    propagate_support,
    seed_connected_component,
    score_feature_map,
    score_features,
)
from .query_engine import CanonicalQueryEngine, QueryResult
from .query_compilers import compile_registered_primitive_seeds
from .query_spec import (
    PrototypeSet,
    QueryIntent,
    QueryModality,
    QuerySpec as TypedQuerySpec,
    RegistrationMode,
    SelectionMode,
    SoftSeedSet,
)
from .support_solver import (
    PrimitiveSupportGraph,
    SupportGraphConfig,
    SupportSolverConfig,
    build_primitive_support_graph,
    select_support_components,
    solve_primitive_support,
)

__all__ = [
    "QueryKind",
    "QuerySpace",
    "QuerySpec",
    "SupportGraph",
    "SupportPropagationConfig",
    "binary_mask",
    "build_support_graph",
    "cosine_bank_torch",
    "cosine_margin_torch",
    "cosine_relevancy_torch",
    "margin_to_relevancy_torch",
    "propagate_support",
    "seed_connected_component",
    "score_feature_map",
    "score_features",
    "CanonicalQueryEngine",
    "PrimitiveSupportGraph",
    "PrototypeSet",
    "QueryIntent",
    "QueryModality",
    "QueryResult",
    "RegistrationMode",
    "SelectionMode",
    "SoftSeedSet",
    "SupportGraphConfig",
    "SupportSolverConfig",
    "TypedQuerySpec",
    "build_primitive_support_graph",
    "compile_registered_primitive_seeds",
    "select_support_components",
    "solve_primitive_support",
]
