base_config: ./lerf_ramen_mutual_calib_10_boundary_ft12.yaml

exp_name: "lerf_ramen_mutual_calib_10_boundary_ft12_cachefix"
output_dir: "/root/RADIO-GS/output/radio_gs/lerf_ramen_mutual_calib_10_boundary_ft12_cachefix"
