base_config: ../../lerf_hybrid_v14_waldo_kitchen_fdh_ws240_240ep.yaml

feature_dir: /root/RADIO-GS/output/canonical_teacher_features/waldo_kitchen
pose_file: ""
pose_dir: /root/RADIO-GS/output/canonical_teacher_features/waldo_kitchen/poses_c2w_colmap_verified
