base_config: ../../lerf_hybrid_v14_ramen_fdh_ws240_240ep.yaml

feature_dir: /mnt/pool/sqy/results/RADIO-GS/output/canonical_teacher_features/ramen_fix4c_exact120_v1
pose_file: ""
pose_dir: /root/RADIO-GS/output/radio_features_lerf/ramen/poses_c2w_colmap_verified
