base_config: ../../lerf_hybrid_v14_figurines_fdh_ws240_240ep.yaml

feature_dir: /root/RADIO-GS/output/canonical_teacher_features/figurines
pose_file: ""
pose_dir: /root/RADIO-GS/output/canonical_teacher_features/figurines/poses_c2w_colmap_verified
