base_config: ../scannet_og/scannet_og_hybrid_v14_scene0200_00.yaml
feature_dir: /root/RADIO-GS/output/radio_features_scannet_og/scene0200_00
val_feature_dir: /root/RADIO-GS/output/radio_features_scannet_og/scene0200_00
feature_height: 60
feature_width: 81
pose_file: /root/RADIO-GS/dataset/scannet_og/scene0200_00/traj_w_c.txt
val_pose_file: /root/RADIO-GS/dataset/scannet_og/scene0200_00/traj_w_c.txt
pose_dir: ""
val_pose_dir: ""
